### ISSUE TITLE
Azure Synapse is listed in multiple places as "Azure Synapse Redshift"

### ISSUE THREAD

**Issue by jeffhlewis** [AdobeDocs/federated-audience-composition.en#1]
Issue in ./help/connections/federated-db.md:

Calling out that we have "Azure Synapse" listed as "Azure Synapse Redshift" in the FAC documentation in multiple places...I'm assuming this was a copy/paste typo?

![image](https://github.com/user-attachments/assets/01af7f0d-36c5-4e96-bbd2-4242338bb688)

**Comment by manbeneat** [comment]
Thanks for the feedbacks! This has been corrected 😊

**Comment by jeffhlewis** [comment]
Closing this request as complete - thanks!
