### ISSUE TITLE
Databricks is also supported by FAC

### ISSUE THREAD

**Issue by pmonjo** [AdobeDocs/federated-audience-composition.en#2]
Issue in ./help/start/release-notes.md

The list of supported data warehouses under _What cloud warehouses are supported?_ is outdated. At least Databricks has been added recently. Please update the list.

Ref: [FAC October '24 release](https://experienceleague.adobe.com/en/docs/federated-audience-composition/using/release-notes#fac-24-10)

**Comment by Alicesnk** [comment]
Thanks for your feedback @pmonjo, the section has been updated. Changes will be live later today.
Internal reference: DOCAC-11341
